logging:
  level:
    com:
      mycompany:
        myapp: INFO
spring:
  application:
    name: JhipsterSampleApplication
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: https://localhost:9443/realms/jhipster
        registration:
          oidc:
            client-id: web_app
            client-secret: web_app
            scope: openid,profile,email
server:
  port: 8080
application:
  security:
    oauth2:
      audience: account,api://default
